# Created by: Kevin Golding <ports@caomhin.org>
# $FreeBSD: head/archivers/py-rarfile/Makefile 412344 2016-04-01 13:29:15Z mat $

PORTNAME=	rarfile
PORTVERSION=	2.7
CATEGORIES=	archivers python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@caomhin.org
COMMENT=	Python module for RAR archive reading

LICENSE=	ISCL

RUN_DEPENDS=	unrar:archivers/unrar

NO_ARCH=	yes
USES=		python:2.7+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
